---
- name: Configure web-server
  hosts: web-server

  tasks:
    - name: Install aptitude using apt
      shell: | 
        sudo apt install docker.io -y
        sudo usermod -aG docker $USER
        newgrp docker
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo systemctl status docker
